version: '3.9'
services:
  # backend:
  #   build: . # ! dot mean create a build from Dockerfile
  #   ports:
  #     - 3001:3001 # port in local computer | port in local container
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db # make backend services related to db services. db services will run first

  db:
    image: postgres:14.1-alpine
    # platform: linux/arm64/v8
    restart: always
    environment:
      POSTGRES_DATABASE: kasi_edu_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres-db:
    driver: local
